#!/bin/bash
set -x

 ## Ask value for mysql root password
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
 read -p 'wordpress_db_name [wp_db]: ' wordpress_db_name
 read -p 'db_root_password [only-alphanumeric]: ' db_root_password
 echo

function installPackages() {
    yum install httpd httpd-utils -y
    yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
    yum install yum-utils -y
    yum-config-manager --enable remi-php56 -y
    yum install php php-mcrypt php-cli php-gd php-curl php-mysql php-ldap php-zip php-fileinfo -y
    yum install  php-gd php-mysql -y
    yum install  php php-common php-mysql php-gd php-xml php-mbstring php-mcrypt php-xmlrpc unzip wget -y
    yum install wget vim -y
    yum install phpmyadmin -y
    wget http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
     yum -y install ./mysql57-community-release-el7-7.noarch.rpm

    yum install mysql-server mysql-client -y

}
function configureMysql() {
    systemctl stop mysqld
    systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
    systemctl start mysqld
    mysql -u root -e "UPDATE mysql.user SET authentication_string = PASSWORD('$db_root_password') WHERE User = 'root' AND Host = 'localhost';"
    mysql -u root -e "FLUSH PRIVILEGES;"
    systemctl unset-environment MYSQLD_OPTS
    systemctl restart mysqld
    mysql -u root -p$db_root_password --connect-expired-password -e "SET PASSWORD = PASSWORD('$db_root_password');"
    mysql -u root -p$db_root_password -e "CREATE DATABASE $wordpress_db_name;"
#    mysql -u root -p$db_root_password -e "GRANT ALL PRIVILEGES ON $wordpress_db_name.* TO 'root'@'localhost' IDENTIFIED BY '$db_root_password';"
    mysql -u root -p$db_root_password -e "FLUSH PRIVILEGES;"



}
function initiateServices(){
    systemctl restart httpd
    systemctl restart mysqld
    systemctl enable httpd
    systemctl enable mysqld
}

function installWP() {
    rm -rf /var/www/html/index.*
    wget -c http://wordpress.org/latest.tar.gz
    tar -xzvf latest.tar.gz
    cp -r wordpress/* /var/www/html/
    chown -R 777 /var/www/html/
    chmod -R 755 /var/www/html/
    cd /var/www/html/
    sudo mv wp-config-sample.php wp-config.php
    sed -i 's/database_name_here/'$wordpress_db_name'/g' wp-config.php
    perl -pi -e "s/username_here/root/g" wp-config.php
    sed -i 's/password_here/'$db_root_password'/g' wp-config.php
    #echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/httpd/conf/httpd.conf
    cat <<EOT >> /etc/httpd/conf/httpd.conf
<VirtualHost *:80>

  DirectoryIndex index.php index.html
  DocumentRoot /var/www/html/

  <Directory /var/www/html>
      Options FollowSymLinks
      AllowOverride All
      Require all granted
  </Directory>

</VirtualHost>
EOT

}



installPackages
configureMysql
initiateServices
installWP
